# Generated by Django 5.1.5 on 2025-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'DailyStatistic',
                'verbose_name_plural': 'Statistics',
                'managed': False,
            },
        ),
    ]
