# Generated by Django 5.1.5 on 2025-01-25 19:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_paymentmethod_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(help_text='Enter the name of the payment method.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug will be automatically generated based on the name if left blank.', unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Contract Amount'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='University Name'),
        ),
    ]
