# Generated by Django 5.1.5 on 2025-01-28 10:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), editable=False, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
