# Generated by Django 5.1.5 on 2025-02-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default=None, max_length=20),
        ),
    ]
