# Generated by Django 5.1.5 on 2025-02-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_total_balance'),
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
    ]
