# Generated by Django 5.1.5 on 2025-02-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsponsor',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(limit_choices_to={'necessary_balance__gt': 0, 'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='student_studentsponsors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsponsor',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
