# Generated by Django 5.1.5 on 2025-02-02 12:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('1000000'))]),
        ),
    ]
