# Generated by Django 5.1.5 on 2025-01-25 15:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='The phone number must be in the Uzbek format (e.g., +998901234567).', regex='^\\+998\\d{9}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('reviewing...', 'Reviewing...'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
            ],
        ),
    ]
