# Generated by Django 5.1.5 on 2025-02-17 13:39

import apps.utils.functions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='sponsor_fullname',
            field=models.CharField(default='fullname', max_length=50, validators=[apps.utils.functions.validators.check_fullname]),
            preserve_default=False,
        ),
    ]
