# Generated by Django 5.1.5 on 2025-01-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_alter_appeal_created_by_alter_appeal_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'verbose_name': 'Appeal', 'verbose_name_plural': 'Appeals'},
        ),
    ]
